import { z } from "zod";

// Define the schema for user validation
export const userSchema = z.object({
  user_id: z.string().uuid().optional(), // Automatically generated by Prisma, usually not required in input
  email: z.string().email("Invalid email address"),
  refresh_Token: z.string().optional(),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters long")
    .regex(/[a-z]/, "Password must include at least one lowercase letter")
    .regex(/[A-Z]/, "Password must include at least one uppercase letter")
    .regex(/\d/, "Password must include at least one number")
    .regex(/[!@#$%^&*]/, "Password must include at least one special character"),
  resetPasswordToken: z.string().optional(), // Optional for reset password functionality
  resetPasswordExpire: z.string().optional(), // Optional for reset password functionality
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().min(1, "Last name is required"),
  phone_number: z
    .string()
    .regex(/^\d{10}$/, "Phone number must be exactly 10 digits"), // Modify as per your phone validation requirements
  role: z.enum(["USER", "ADMIN"], "Role must be USER or ADMIN"),
  wedding_date: z.string().datetime().optional(), // Optional and should be a valid ISO date-time string
  wedding_location: z.string().optional(), // Optional string
  created_at: z.string().datetime().optional(), // Auto-generated by Prisma
});

// Schema for user updates (all fields optional)
export const updateUserSchema = userSchema.partial();

// Schema for user login
export const loginSchema = z.object({
  email: z.string().email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters long"),
});

// Schema for password reset
export const resetPasswordSchema = z.object({
  resetToken: z.string(),
  newPassword: z
    .string()
    .min(8, "Password must be at least 8 characters long")
    .regex(/[a-z]/, "Password must include at least one lowercase letter")
    .regex(/[A-Z]/, "Password must include at least one uppercase letter")
    .regex(/\d/, "Password must include at least one number")
    .regex(/[!@#$%^&*]/, "Password must include at least one special character"),
});
